-- Reference schema + RLS (remote applied via Supabase migrations)

create table public.games (
  id bigint generated by default as identity primary key,
  name text not null,
  storage_path text,
  created_at timestamptz default now()
);

alter table public.games enable row level security;

create policy "games_select_anon"
  on public.games
  for select
  to anon, authenticated
  using (true);

-- SGS generate: insert row → upload HTML → update storage_path
create policy "games_insert_anon"
  on public.games
  for insert
  to anon, authenticated
  with check (true);

create policy "games_update_anon"
  on public.games
  for update
  to anon, authenticated
  using (true)
  with check (true);

-- rollback on failed upload
create policy "games_delete_anon"
  on public.games
  for delete
  to anon, authenticated
  using (true);
