-- Reference schema + RLS (matches remote migration games_add_user_id_auth_rls)

create table public.games (
  id bigint generated by default as identity primary key,
  name text not null,
  storage_path text,
  user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz default now()
);

alter table public.games enable row level security;

-- Feed: authenticated users can read all games
create policy "games_select_authenticated"
  on public.games
  for select
  to authenticated
  using (true);

-- Own rows only for writes
create policy "games_insert_own"
  on public.games
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "games_update_own"
  on public.games
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "games_delete_own"
  on public.games
  for delete
  to authenticated
  using (auth.uid() = user_id);
